version: '3.8'

services:
  monolithic-core:
    build: ./monolithic-core
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/ecommerce
      - REDIS_HOST=redis
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - mongodb
      - redis
      - kafka

  payment-service:
    build: ./payment-service
    ports:
      - "3001:3001"
    environment:
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - kafka

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - monolithic-core

  invoice-service:
    build: ./invoice-service
    ports:
      - "3002:3002"
    environment:
      - KAFKA_BROKERS=kafka:9092
      - MONGODB_URI=mongodb://mongodb:27017/invoices
    depends_on:
      - kafka
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "payment_completed:1:1,invoice_created:1:1"
    depends_on:
      - zookeeper

volumes:
  mongodb_data: